- name: start.yml | ENTRY
  debug:
   msg: start.yml | ansible-filebeat | ENTRY |
   verbosity: 3
  tags: always

- name: start.yml | start
  service:
    name: filebeat
    state: started
    enabled: true

- name: start.yml | EXIT
  debug:
   msg: start.yml | ansible-filebeat | EXIT |
   verbosity: 3
  tags: always

