- name: Uninstall winlogbeat
  win_shell: sc delete "winlogbeat"

- name: Remove other winlogbeat installations
  win_shell: |
    $version="{{ winlogbeat_service.version }}"
    Get-ChildItem -Path "{{ winlogbeat_service.install_path_64 }}" | Where-Object {$_.Name -CNotMatch $version} | Remove-Item -Recurse
  
